default send_exemplars to true in remote_write config
grafana/agent pull request #1352
Opened 2022-02-02 22:11 UTC by rlankfo

#### PR Description 

This PR updates our dependency on `grafana/prometheus` to a version that has defaults send_exemplars to true in remote_write config. See https://github.com/grafana/prometheus/pull/26

Closes https://github.com/grafana/agent/issues/1116

#### Which issue(s) this PR fixes 

#### Notes to the Reviewer

I'm open to suggestions on other/better ways to accomplish this. My thinking is prometheus will not want to upstream this change.

If we do end up going this route, once https://github.com/grafana/prometheus/pull/26 is merged, I will update the version in go.mod instead of using the commit from my branch.

#### PR Checklist

- [ ] CHANGELOG updated 
- [ ] Documentation added
- [ ] Tests updated

2022-02-03 08:40 UTC, tpaschalis commented
I think two different ways we could achieve this would be a) using the existing init function to set that exported variable to true, or b) setting it in our DefaultGlobalConfig and handling it in ApplyDefaults. 

I don't have a strong opinion and I like the simplicity here, but these options might be worth it if we'd like to depend less on our custom Prometheus fork going forward. WDYT?

2022-02-03 14:11 UTC, mattdurham commented
I would like to wait for the prometheus ticket to get merged. Given it is prometheus and our linking to prometheus is tricky already.

2022-02-03 14:11 UTC, mattdurham commented
And of course, I hit the wrong button and closed this PR instead of just submitting feedback. Reopened, apologies for email spam.

2022-02-03 14:12 UTC, mattdurham requested changes
Would prefer to wait for merge in prometheus fork.

2022-02-08 16:20 UTC, tpaschalis approved these changes
LGTM! 👌

2022-02-08 16:56 UTC, bboreham approved these changes

2022-02-08 19:55 UTC, mattdurham approved these changes
👍

2022-02-08 19:55 UTC, merged