enable extra scrape metrics
grafana/agent pull request #1379
Opened 2022-02-10 22:35 UTC by rlankfo

#### PR Description 

This adds a feature flag for enabling [extra scrape metrics](https://prometheus.io/docs/prometheus/2.31/feature_flags/#extra-scrape-metrics). 

#### Which issue(s) this PR fixes 

Closes https://github.com/grafana/agent/issues/1073

#### Notes to the Reviewer

#### PR Checklist

- [ ] CHANGELOG updated 
- [ ] Documentation added
- [ ] Tests updated

2022-02-11 13:47 UTC, mattdurham commented
Thoughts on adding a tiny unit test to make sure it propagates?

2022-02-11 14:35 UTC, rfratto reviewed
$0.02: I think we can enable this by default, and make it optional if there ends up being problems. Prometheus can be a little more aggressive with feature flags, but I think this is small enough to just enable.

2022-02-11 16:06 UTC, rlankfo commented
> $0.02: I think we can enable this by default, and make it optional if there ends up being problems. Prometheus can be a little more aggressive with feature flags, but I think this is small enough to just enable.

@rfratto It does seem minor so I agree we could just enable this by default if we want access to these metrics. My only concern would be unexpected increase in cardinality caused by these additional metrics and their labels for users who have a substantial amount of scrape targets. I believe this is why prometheus initially wrapped this in a feature flag.

2022-02-11 17:41 UTC, rfratto commented
> My only concern would be the unexpected increase in cardinality caused by these additional metrics and their labels for users who have a substantial amount of scrape targets. I believe this is why prometheus initially wrapped this in a feature flag.

That's a good point. If we want to make it opt-out, maybe it should be a permanent flag or a YAML option? Feature flag implies that it will eventually be permanently on by default once it graduates out of experimental.

2022-02-11 17:50 UTC, rlankfo commented
> That's a good point. If we want to make it opt-out, maybe it should be a permanent flag or a YAML option? Feature flag implies that it will eventually be permanently on by default once it graduates out of experimental.

Personally I think the feature flag makes sense here (opt-in) vs deviating from what [Prometheus is doing](https://prometheus.io/docs/prometheus/latest/feature_flags/#extra-scrape-metrics) with these.  In their docs they state the behavior of these features could change in future releases, or they *may* end up permanently on by default, which seems reasonable for this feature.

2022-02-11 18:02 UTC, rlankfo commented
> the behavior of these features could change in future releases, or they _may_ end up permanently on by default

Expanding on this a bit in general, it probably isn't a good decision to enable experimental Prometheus features by default in the agent.

2022-02-15 13:56 UTC, mattdurham commented
I am for leaving it as a feature flag is legit if there is considerable uncertainty within Prometheus about the future of it.

2022-02-15 14:55 UTC, mattdurham requested changes
LGTM, aside from a tiny test

2022-02-15 19:32 UTC, mattdurham approved these changes
Thanks!

2022-02-15 21:27 UTC, mattdurham commented
Apologies, one more thing. We should document this in the configuration guide somewhere. Note sure if [here](https://github.com/grafana/agent/blob/585e058c64fac7caec907471eeede33c93aab6d2/docs/user/configuration/_index.md) is the best place? Given our increasing usage of feature flags somewhere dedicated might make sense but that doesn't have to be decided in this PR has long as we have some doc somewhere.

2022-02-16 17:28 UTC, rlankfo commented
> Given our increasing usage of feature flags somewhere dedicated might make sense but that doesn't have to be decided in this PR has long as we have some doc somewhere.

I think this makes sense -- I'll go ahead and address https://github.com/grafana/agent/issues/1383 in this PR and create a dedicated section in the docs.

2022-03-16 14:08 UTC, rfratto commented
@rlankfo gentle reminder about this :)

2022-04-18 14:26 UTC, rlankfo commented
> @rlankfo gentle reminder about this :)

Rebased and updated docs. This should be good to go, sorry for delay on this

2022-04-18 15:34 UTC, rfratto approved these changes

2022-04-18 15:35 UTC, merged