Add windows Grafana agent installation script
grafana/agent pull request #1707
Opened 2022-05-16 22:24 UTC by mshahzeb

Hi team along with the effort of upgrading the Windows integration - I have written a powershell script to automate the installation and configuration of Grafana agent on Windows. Similar to the linux agent script - the powershell script:

1. Downloads the Grafana agent windows installer
2. Installs the Grafana agent using the installer in silent mode
3. Gets the agent config from integration API and converts it to YAML
4. Copies over the config and restarts the agent

The steps needed are as below:
```
# Download the Powershell script - run the following command in command prompt:
curl -L https://storage.googleapis.com/grafanalabs-integration-assets/windows/scripts/grafanacloud-install.ps1 --output grafanacloud-install.ps1

# Then execute the script from a command prompt running with administrator privileges:
powershell -executionpolicy Bypass -File “.\grafanacloud-install.ps1" -GCLOUD_STACK_ID <Gcloud Stack ID> -GCLOUD_API_KEY <Gcloud API Key> -GCLOUD_API_URL <Gcloud API Url>
```

The script is written to be compatible with Powershell 3.0 and above

2022-05-18 13:38 UTC, mattdurham commented on production/grafanacloud-install.ps1
> +	Write-Host "Saving and updatig agent configuration file"
nite: updating

2022-05-18 13:39 UTC, mattdurham requested changes
LGTM, may need to trigger a new build though to get the CI to pass

2022-05-18 23:00 UTC, mshahzeb commented on production/grafanacloud-install.ps1
> +$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
Thanks! Updated :)

2022-05-18 23:00 UTC, mshahzeb commented on production/grafanacloud-install.ps1
> +$response = Invoke-WebRequest $CONFIG_URI -Method 'GET' -Headers $headers
I had issues while using convert to json with Invoke-RestMethod - it has some auto conversion to json mechanism that was not working well, so reverted to usig Invoke-WebRequest.

2022-05-19 15:47 UTC, mattdurham approved these changes
Looks great

2022-05-19 15:47 UTC, merged