Setup for RC build v0.26.0.rc.0
grafana/agent pull request #1876
Opened 2022-07-08 13:55 UTC by mattdurham

#### PR Description

v0.26.0-rc0 release

#### PR Checklist

- [X] CHANGELOG updated

2022-07-11 17:43 UTC, rfratto requested changes
You're missing updating references to the previous version which don't start with v (see grafanacloud-install.sh)

2022-07-11 17:43 UTC, rfratto commented on CHANGELOG.md
> +-------------------------
Update to today?

2022-07-12 00:50 UTC, rfratto commented
I'd recommend creating a separate branch to cherry pick things into main to avoid needing to keep release-v0.26 mergable back upstream

2022-07-12 01:19 UTC, rlankfo commented
I don't think it makes sense to merge the release candidate image tags/version updates to main. IMO they can just live on the release branch. Once the final release is cut, then the image tags can be merged into main.

2022-07-12 13:12 UTC, closed without merging