Do not action if the component is not running
grafana/agent pull request #2710
Opened 2023-01-10 11:36 UTC by ptodev

#### PR Description
Fixes #2216. The `prometheus.relabel` and  `prometheus.remote_write` components will now error if data is being sent to them while they are stopped. The reason they are in memory and stopped is that during a config refresh they got deleted, but a component which references them keeps a reference to them since it has to be preserved to be in the last good state (the state prior to the refresh). An issue has been raised to question this behaviour (#2709) - it may be better to preserve the last good state of the graph as a whole instead of the last good state of the individual components. If that were the case, we also would be less likely to see bugs such as this one.

#### Test evidence
1. An agent was ran locally with this river file:
```
prometheus.scrape "default" {
	targets    = [{"__address__" = "localhost:12345"}]
	forward_to = [prometheus.relabel.filter.receiver]
}

prometheus.relabel "filter" {
	rule {
		source_labels = ["__name__"]
		regex         = "(.+)"
		replacement   = "api_server"
		target_label  = "service"
	}
	forward_to = [prometheus.remote_write.prom.receiver]
}

prometheus.remote_write "prom" {
	endpoint {
		url = "http://localhost:9009/api/v1/push"
	}
}
```

2. Then the river file was changed to this:
```
prometheus.scrape "default" {
	targets    = [{"__address__" = "localhost:12345"}]
	forward_to = [prometheus.relabel.filter.receiver]
}

prometheus.remote_write "prom" {
	endpoint {
		url = "http://localhost:9009/api/v1/push"
	}
}
```

3. The config was refreshed with this command: `curl localhost:12345/-/reload`

4. The new `component is not running` warnings can be seen in the agent output:
```
% AGENT_MODE=flow ./grafana-agent run /Users/paulintodev/flow_tutorial/tutorials/flow_configs/relabel.river

ts=2023-01-10T10:31:55.289245Z level=info msg="now listening for http traffic" addr=127.0.0.1:12345
ts=2023-01-10T10:31:55.289302Z level=info msg="running usage stats reporter"
ts=2023-01-10T10:31:55.289594Z level=info trace_id=d53f49e021568fdfa2ad9a30a381566a msg="starting complete graph evaluation"
ts=2023-01-10T10:31:55.291231Z level=info component=prometheus.remote_write.prom subcomponent=wal msg="replaying WAL, this may take a while" dir=data-agent/prometheus.remote_write.prom/wal/prometheus.remote_write.prom/wal
ts=2023-01-10T10:31:55.29216Z level=info component=prometheus.remote_write.prom subcomponent=wal msg="WAL segment loaded" segment=0 maxSegment=10
ts=2023-01-10T10:31:55.293059Z level=info component=prometheus.remote_write.prom subcomponent=wal msg="WAL segment loaded" segment=1 maxSegment=10
ts=2023-01-10T10:31:55.29475Z level=info component=prometheus.remote_write.prom subcomponent=wal msg="WAL segment loaded" segment=2 maxSegment=10
ts=2023-01-10T10:31:55.296859Z level=info component=prometheus.remote_write.prom subcomponent=wal msg="WAL segment loaded" segment=3 maxSegment=10
ts=2023-01-10T10:31:55.297436Z level=info component=prometheus.remote_write.prom subcomponent=wal msg="WAL segment loaded" segment=4 maxSegment=10
ts=2023-01-10T10:31:55.298096Z level=info component=prometheus.remote_write.prom subcomponent=wal msg="WAL segment loaded" segment=5 maxSegment=10
ts=2023-01-10T10:31:55.298158Z level=info component=prometheus.remote_write.prom subcomponent=wal msg="WAL segment loaded" segment=6 maxSegment=10
ts=2023-01-10T10:31:55.299284Z level=info component=prometheus.remote_write.prom subcomponent=wal msg="WAL segment loaded" segment=7 maxSegment=10
ts=2023-01-10T10:31:55.299335Z level=info component=prometheus.remote_write.prom subcomponent=wal msg="WAL segment loaded" segment=8 maxSegment=10
ts=2023-01-10T10:31:55.299387Z level=info component=prometheus.remote_write.prom subcomponent=wal msg="WAL segment loaded" segment=9 maxSegment=10
ts=2023-01-10T10:31:55.299425Z level=info component=prometheus.remote_write.prom subcomponent=wal msg="WAL segment loaded" segment=10 maxSegment=10
ts=2023-01-10T10:31:55.299859Z component=prometheus.remote_write.prom subcomponent=rw level=info remote_name=eb37ce url=http://localhost:9009/api/v1/push msg="Starting WAL watcher" queue=eb37ce
ts=2023-01-10T10:31:55.299871Z component=prometheus.remote_write.prom subcomponent=rw level=info remote_name=eb37ce url=http://localhost:9009/api/v1/push msg="Starting scraped metadata watcher"
ts=2023-01-10T10:31:55.299979Z component=prometheus.remote_write.prom subcomponent=rw level=info remote_name=eb37ce url=http://localhost:9009/api/v1/push msg="Replaying WAL" queue=eb37ce
ts=2023-01-10T10:31:55.304789Z level=info trace_id=d53f49e021568fdfa2ad9a30a381566a msg="finished complete graph evaluation" duration=15.241083ms
ts=2023-01-10T10:31:55.304804Z level=info msg="scheduling loaded components"
ts=2023-01-10T10:32:23.737252Z component=prometheus.remote_write.prom subcomponent=rw level=info remote_name=eb37ce url=http://localhost:9009/api/v1/push msg="Done replaying WAL" duration=28.437608875s
ts=2023-01-10T10:36:53.566348Z level=info trace_id=338bf209f96350a35c92b1872c9a77f2 msg="starting complete graph evaluation"
ts=2023-01-10T10:36:53.575302Z level=info trace_id=338bf209f96350a35c92b1872c9a77f2 msg="finished complete graph evaluation" duration=9.004458ms
ts=2023-01-10T10:36:53.575352Z level=info msg="scheduling loaded components"
ts=2023-01-10T10:37:17.721105Z level=info trace_id=9288b4d0af95cb58c9965a4dbad3b599 msg="starting complete graph evaluation"
ts=2023-01-10T10:37:17.730633Z level=info trace_id=9288b4d0af95cb58c9965a4dbad3b599 msg="finished complete graph evaluation" duration=9.636292ms
ts=2023-01-10T10:37:17.730693Z level=info msg="scheduling loaded components"
ts=2023-01-10T10:37:17.730735Z level=info component=prometheus.relabel.filter msg="component exited"
ts=2023-01-10T10:37:23.714297Z level=warn component=prometheus.scrape.default scrape_pool=prometheus.scrape.default target=http://localhost:12345/metrics msg="Append failed" err="1 error occurred:\n\t* the prometheus.relabel component is not running\n\n"
ts=2023-01-10T10:37:23.714382Z level=warn component=prometheus.scrape.default scrape_pool=prometheus.scrape.default target=http://localhost:12345/metrics msg="Appending scrape report failed" err="1 error occurred:\n\t* the prometheus.relabel component is not running\n\n"
```

2023-01-10 15:35 UTC, rfratto requested changes

2023-01-10 15:35 UTC, rfratto commented on CHANGELOG.md
> +- Flow: `prometheus.relabel` and `prometheus.relabel` will now error if they are not running. (@ptodev)
```suggestion
- Flow: `prometheus.relabel` and `prometheus.relabel` will now return error on receiving metrics if they are not running. (@ptodev)
```

2023-01-11 10:00 UTC, ptodev commented on CHANGELOG.md
> +- Flow: `prometheus.relabel` and `prometheus.relabel` will now error if they are not running. (@ptodev)
Whoops, thank you, I will fix it.

2023-01-11 13:25 UTC, rfratto approved these changes
Thanks! LGTM but looks like you're running into some legitimate CI failures.

2023-01-11 13:58 UTC, tpaschalis reviewed
Nothing major to add, looks good!

A small test could be nice if it's not too hard to add. ^^ (kicking off the component, then cancelling the context and appending should return the error)

2023-01-12 16:21 UTC, ptodev commented
> Nothing major to add, looks good!
> 
> A small test could be nice if it's not too hard to add. ^^ (kicking off the component, then cancelling the context and appending should return the error)

The problem is that the cancel() function for the context is not synchronous, so I'd have to add some way to make sure the component finished before appending at the end of the test.

2023-01-12 16:23 UTC, rfratto commented
> The problem is that the cancel() function for the context is not synchronous, so I'd have to add some way to make sure the component finished before appending at the end of the test.

You can use `require.Eventually` or [`util.Eventually`](https://github.com/grafana/agent/blob/main/pkg/util/eventually.go) to test asynchronous behaviors.

2023-01-12 16:32 UTC, ptodev commented
If you think it's a good idea I could try it, but I'm a bit weary of using real clocks in unit tests. It can make the tests more unreliable and interferes with debuggers. In the past I used to almost always mock the clock, and I'm surprised we don't do it here too.

2023-01-12 22:08 UTC, merged