chore: add contextual attributes to faro measurement
grafana/agent pull request #4975
Opened 2023-08-28 16:03 UTC by codecapitano

#### PR Description
In the Faro Web-SDK we added an option to provide additional contextual attributes to the measurements payload.
To enable this we need to update the agent as well.

#### Which issue(s) this PR fixes

#### Notes to the Reviewer
Just for reference here are the PRs which make the needed changes to the Faro Receiver and the Faro Web-SDK.
* [PR Receiver](https://github.com/grafana/app-o11y-kwl-endpoint/pull/262)
* [PR Docs](https://github.com/grafana/website/pull/15059)

#### PR Checklist

- [x] CHANGELOG.md updated
- [x] Tests updated

2023-08-28 16:37 UTC, rlankfo approved these changes
LGTM for the `MeasurementContext`.  I had one question about adding `Type` but I'm not sure if it's necessary in this PR.

2023-08-28 16:37 UTC, rlankfo commented on pkg/integrations/v2/app_agent_receiver/payload.go
> +	Type      string             `json:"type,omitempty"`
`Type` doesn't appear to be included in the `KeyVal` object. Do we want to add this to `func (m Measurement) KeyVal() *KeyVal` ? 

```go
KeyValAdd(kv, "type", m.Type)
```

2023-08-28 17:13 UTC, rlankfo commented
@codecapitano looks like there are some additional test cases we should update:

```
--- FAIL: TestExportLogs (0.01s)
    logs_exporter_test.go:103: 
        	Error Trace:	/Users/runner/work/agent/agent/pkg/integrations/v2/app_agent_receiver/logs_exporter_test.go:103
        	Error:      	Not equal: 
        	            	expected: "timestamp=\"2021-09-30 10:46:17.68 +0000 UTC\" kind=measurement ttfb=14.000000 ttfcp=22.120000 ttfp=20.120000 traceID=abcd spanID=def sdk_name=grafana-frontend-agent sdk_version=1.0.0 app_name=testapp app_release=0.8.2 app_version=abcdefg app_environment=production user_email=geralt@kaermorhen.org user_id=123 user_username=domasx2 user_attr_foo=bar session_id=abcd session_attr_time_elapsed=100s page_url=https://example.com/page browser_name=chrome browser_version=88.12.1 browser_os=linux browser_mobile=false view_name=foobar"
        	            	actual  : "timestamp=\"2021-09-30 10:46:17.68 +0000 UTC\" kind=measurement ttfb=14.000000 ttfcp=22.120000 ttfp=20.120000 traceID=abcd spanID=def context_hello=world sdk_name=grafana-frontend-agent sdk_version=1.0.0 app_name=testapp app_release=0.8.2 app_version=abcdefg app_environment=production user_email=geralt@kaermorhen.org user_id=123 user_username=domasx2 user_attr_foo=bar session_id=abcd session_attr_time_elapsed=100s page_url=https://example.com/page browser_name=chrome browser_version=88.12.1 browser_os=linux browser_mobile=false view_name=foobar"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-timestamp="2021-09-30 10:46:17.68 +0000 UTC" kind=measurement ttfb=14.000000 ttfcp=22.120000 ttfp=20.120000 traceID=abcd spanID=def sdk_name=grafana-frontend-agent sdk_version=1.0.0 app_name=testapp app_release=0.8.2 app_version=abcdefg app_environment=production user_email=geralt@kaermorhen.org user_id=123 user_username=domasx2 user_attr_foo=bar session_id=abcd session_attr_time_elapsed=100s page_url=https://example.com/page browser_name=chrome browser_version=88.12.1 browser_os=linux browser_mobile=false view_name=foobar
        	            	+timestamp="2021-09-30 10:46:17.68 +0000 UTC" kind=measurement ttfb=14.000000 ttfcp=22.120000 ttfp=20.120000 traceID=abcd spanID=def context_hello=world sdk_name=grafana-frontend-agent sdk_version=1.0.0 app_name=testapp app_release=0.8.2 app_version=abcdefg app_environment=production user_email=geralt@kaermorhen.org user_id=123 user_username=domasx2 user_attr_foo=bar session_id=abcd session_attr_time_elapsed=100s page_url=https://example.com/page browser_name=chrome browser_version=88.12.1 browser_os=linux browser_mobile=false view_name=foobar
        	Test:       	TestExportLogs
```

2023-08-28 17:14 UTC, rlankfo requested changes
test cases + changelog formatting

2023-08-28 18:29 UTC, rlankfo commented on CHANGELOG.md
> +## Main (unreleased)
looks like the changelog was formatted. prettier on save? :D  we should make sure we only add the entry we need to this file.

2023-08-29 08:33 UTC, marctc commented on pkg/integrations/v2/app_agent_receiver/payload.go
> +// ExceptionContext is a string to string map structure that
This comment doesn't match the name of the type

2023-08-29 16:02 UTC, rlankfo approved these changes
lgtm!

2023-08-31 08:54 UTC, merged