5679 flow mode service discovery deletes jobs with same prefix
grafana/agent pull request #5844
Opened 2023-11-23 17:34 UTC by Paul424

#### PR Description

#### Which issue(s) this PR fixes

Fixes #5679

#### Notes to the Reviewer
Two interfaces had to be inserted to enable mocking the actual discovery-manager and scrape-manager; if this should be done differently please let me know through the PR so i can rework.

#### PR Checklist
- [x] CHANGELOG.md updated
- [x] Tests updated

2023-11-23 17:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/agent?pullRequest=5844) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/agent?pullRequest=5844) before we can accept your contribution.<br/><hr/>**Paul Bormans** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/agent?pullRequest=5844) it.</sub>

2023-11-27 14:54 UTC, captncraig commented on component/prometheus/operator/common/crdmanager.go
> +type DiscoveryManager interface {
Can you put these interfaces in a seperate file. I understand why you added them, and I do believe they are still useful, but this file is large enough as it is.

2023-11-27 14:56 UTC, captncraig approved these changes

2023-11-27 15:01 UTC, captncraig commented
Oh, I think I see one complication here. For podmonitors and servicemonitors, the job name is `podMonitor/ns/name/1`, but for probes it is just `probe/ns/name`, so we do a more generous prefix match to cover both cases. So we need to do something different for probes.

Maybe if `c.kind` is probe, clearConfigs should do something different, like a full equality match?

Or maybe the string matching on job name is silly, and we should create a full lookup of monitor names to a list of map keys, so we rely on fewer assumptions?

2023-11-27 15:02 UTC, captncraig requested changes
I think we need to address the issue with probes before merging.

2023-11-27 15:19 UTC, captncraig commented
I'm thinking something like this: https://github.com/grafana/agent/commit/7268b5f856f54de3aba01b2489f1f2d3d73b951d, although I haven't tested it or merged with your tests. What do you think?

2023-11-27 16:40 UTC, paul-bormans commented
> I'm thinking something like this: [7268b5f](https://github.com/grafana/agent/commit/7268b5f856f54de3aba01b2489f1f2d3d73b951d), although I haven't tested it or merged with your tests. What do you think?

Let me check (tomorrow); perhaps I could write tests for probes first to make sure we don't break anything.

2023-11-27 17:42 UTC, captncraig commented
Thank you. I've incorporated your changes into #5862 since we would like to get this fix merged asap and possibly into a patch release. Thank you so much for tracking this one down.

2023-11-27 17:42 UTC, closed without merging