feat(exporter/windows): expose physical_disk collector
grafana/agent pull request #5927
Opened 2023-12-06 17:04 UTC by hainenber

#### PR Description

#### Which issue(s) this PR fixes

Fixes #5882 

#### Notes to the Reviewer
The new collector is set as default by`windows_exporter`. Should we follow the course or keep it as non-default to keep it simpler?

#### PR Checklist

- [x] CHANGELOG.md updated
- [x] Documentation added
- [x] Tests updated
- [x] Config converters updated

2023-12-11 17:46 UTC, mattdurham commented
We should decide a policy going forward on it. Technically we have said that changing metrics is not a breaking change. Do we have a feel for how many metrics it creates?

2023-12-19 15:24 UTC, hainenber commented
There are [11 new metrics](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.physical_disk.md#metrics) if this is enabled by default.

2023-12-19 17:56 UTC, clayton-cornell reviewed
Minor doc suggestion

2023-12-19 17:56 UTC, clayton-cornell commented on docs/sources/static/configuration/integrations/windows-exporter-config.md
> +    # Maps to collector.logical_disk.disk-include in windows_exporter
```suggestion
    # Maps to collector.logical_disk.disk-include in windows_exporter.
```

2023-12-19 17:56 UTC, clayton-cornell commented on docs/sources/static/configuration/integrations/windows-exporter-config.md
> +    # Maps to collector.logical_disk.disk-exclude in windows_exporter
```suggestion
    # Maps to collector.logical_disk.disk-exclude in windows_exporter.
```

2023-12-26 14:42 UTC, mattdurham commented
Looks good enabled automerge once conflicts are resolved.

2023-12-26 14:42 UTC, mattdurham approved these changes
LGTM

2024-01-10 19:23 UTC, clayton-cornell approved these changes

2024-01-11 14:47 UTC, mattdurham commented on pkg/integrations/windows_exporter/config_windows.go
> +		Include: collector.ConfigDefaults.PhysicalDisk.DiskInclude
Missing a comma here

2024-01-11 14:47 UTC, mattdurham requested changes
Need a comma

2024-01-11 14:49 UTC, mattdurham approved these changes
lets check now

2024-01-11 15:40 UTC, merged