feat(server/http): allow Basic Auth to be configurable for web UI
grafana/agent pull request #6018
Opened 2023-12-22 17:26 UTC by hainenber

#### PR Description

#### Which issue(s) this PR fixes

Fixes #6008 

#### Notes to the Reviewer

#### PR Checklist

- [x] CHANGELOG.md updated
- [x] Documentation added
- [ ] Tests updated
- [ ] Config converters updated

2023-12-22 19:50 UTC, tunguyen9889 commented on docs/sources/flow/reference/cli/run.md
> +* `server.http.basic-auth-filepath`: Absolute path to file containing user and hashed password for Basic Auth (default `""`, signifies disabled).
```suggestion
* `--server.http.basic-auth-filepath`: Absolute path to file containing user and hashed password for Basic Auth (default `""`, signifies disabled).
```

2024-01-06 08:25 UTC, hainenber commented
Basic Auth creds are prompted when trying to access agent's `web` UI, including component routes

![image](https://github.com/grafana/agent/assets/41283691/27bbe9b6-0762-49da-bef9-73e7ff356da6)
![image](https://github.com/grafana/agent/assets/41283691/25ed4a3f-5f05-4c16-a691-82776f8a4cd5)

Operational routes, i.e. `/debug/pprof`, `/metrics`, `/-/ready` and alikes are left alone
![image](https://github.com/grafana/agent/assets/41283691/41b5bc10-f090-4b34-a4eb-76a1955719d1)
![image](https://github.com/grafana/agent/assets/41283691/2661b6f1-cbcd-4551-b16b-f9a272e32cd3)
![image](https://github.com/grafana/agent/assets/41283691/ae863d1f-34c5-428a-9fc2-ca30ee0ab0b2)

2024-01-09 17:17 UTC, clayton-cornell reviewed
Doc changes are really small in this PR. OK as-is

2024-01-12 17:26 UTC, clayton-cornell commented
@grafana/grafana-agent-maintainers This probably needs a once-over by the dev team

2024-01-15 07:49 UTC, tpaschalis requested changes
Hey there 👋  While this looks promising, we'd like to hold off of it for now after some discussion.

The rationale is that for common deployment methods, it's easy enough to achieve the same functionality with a separate layer (eg. using some authentication proxy or mLTS). 

I like how we've contained everything to the UI service in this PR, but maintaining this Agent-side would eventually mean adding more authentication methods and/or extending it to the HTTP service which requires some more care.

If we decide to revisit, we could certainly revive this PR and use it as the base!

2024-01-17 15:04 UTC, closed without merging