Added curl installation
grafana/agent pull request #6297
Opened 2024-02-05 11:45 UTC by PaniniHode

#### PR Description
Added curl installation for proper docker healthcheck setup

#### Which issue(s) this PR fixes
Fixes #3187

#### Notes to the Reviewer

#### PR Checklist
- [ ] CHANGELOG.md updated
- [ ] Documentation added
- [ ] Tests updated
- [ ] Config converters updated

2024-02-05 11:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/agent?pullRequest=6297) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/agent?pullRequest=6297) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/agent?pullRequest=6297) it.</sub>

2024-02-08 14:16 UTC, tpaschalis requested changes
I'd like for us to first explore if this has any new usecases other than a shortcut for a couple of commands.

Adding a new depencency of an actively-maintained tool with such a large range of features and potential false-positive CVEs it might be flagged should be balanced with an actual improvement.

2025-03-26 02:15 UTC, karlskewes commented
> I'd like for us to first explore if this has any new usecases other than a shortcut for a couple of commands.
> 
> Adding a new depencency of an actively-maintained tool with such a large range of features and potential false-positive CVEs it might be flagged should be balanced with an actual improvement.

Is this still under consideration?
An alternative is `wget` and commonly found in container images.

Just hit this adding a health check for Grafana Alloy deployed on AWS ECS.

2026-07-24 14:11 UTC, Grafana-Productivity-Admin commented
Closing this pull request: the repository is being archived and transferred to cold storage.

2026-07-24 14:11 UTC, closed without merging