[Fixes #6565] Implement Luhn Loki processor
grafana/agent pull request #6574
Opened 2024-02-29 20:52 UTC by blockloop

#### PR Description

This adds a Luhn processor to the Loki pipeline to filter credit card numbers based on the [Luhn algorithm](https://en.wikipedia.org/wiki/Luhn_algorithm)

#### Which issue(s) this PR fixes

Fixes #6565

#### Notes to the Reviewer

The unit tests pass, but I'm not 100% sure how to run some integration tests. I'm sure I'm missing some other requirement as well. Any pointers welcome.

#### PR Checklist

- [ ] CHANGELOG.md updated
- [ ] Documentation added
- [x] Tests updated
- [ ] Config converters updated

2024-02-29 20:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/agent?pullRequest=6574) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/agent?pullRequest=6574) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/agent?pullRequest=6574) it.</sub>

2024-02-29 21:10 UTC, mattdurham commented
Thanks for the PR! Some things to add would be comments to the code (link to wikipedia on luhn maybe?) and will need some documentation for the stage added to https://github.com/grafana/agent/blob/main/docs/sources/flow/reference/components/loki.process.md

2024-02-29 21:57 UTC, blockloop commented
@mattdurham I updated with some comments and added the docs to the link. LMK if there's anything else I need to do.

2024-03-01 18:21 UTC, blockloop commented on docs/sources/flow/reference/components/loki.process.md
> +time=2012-11-01T22:08:41+00:00 app=loki level=WARN duration=125 message="credit card approved 4716415709052638" extra="user=foo"
The card has to pass the Luhn filter. I generated it with https://developer.paypal.com/tools/sandbox/card-testing/

2024-03-01 18:23 UTC, blockloop commented on docs/sources/flow/reference/components/loki.process.md
> +time=2012-11-01T22:08:41+00:00 app=loki level=WARN duration=125 message="credit card approved 4716415709052638" extra="user=foo"
I'll update with one from https://developer.paypal.com/tools/sandbox/card-testing/

2024-03-01 18:24 UTC, blockloop commented on docs/sources/flow/reference/components/loki.process.md
> +time=2012-11-01T22:08:41+00:00 app=loki level=WARN duration=125 message="credit card approved 4716415709052638" extra="user=foo"
Done. Let me know if that works @clayton-cornell

2024-03-01 18:32 UTC, clayton-cornell commented on docs/sources/flow/reference/components/loki.process.md
> +time=2012-11-01T22:08:41+00:00 app=loki level=WARN duration=125 message="credit card approved 4716415709052638" extra="user=foo"
That works :-) As long as it's one that's a public test card number or something clearly not a potentially "real" card number, we are all good.

2024-03-01 18:33 UTC, clayton-cornell commented
@mattdurham I'm happy with the doc additions and am ready to sign off. Over to you for final code approval. :-)

2024-03-01 18:40 UTC, blockloop commented
Thanks @clayton-cornell 

@mattdurham I wasn't able to run this to do integration testing. The tests work well but I haven't witnessed it in the pipeline. If you have any integration tests that would be nice.

2024-03-04 14:34 UTC, mattdurham approved these changes
Thank you, looks good to me!

2024-03-04 14:35 UTC, mattdurham commented
There are some linting errors `validateLuhnFilterConfig is unused` along with the new, can you take another look at those?

2024-03-04 14:36 UTC, mattdurham requested changes
There are some unused functions that need to be resolved or hooked up.

2024-03-07 15:11 UTC, blockloop commented
@mattdurham I realized I left out some required implementation to wire up the Luhn filter that was causing the unused code errors. I think it should be okay now.

2024-03-15 11:45 UTC, clayton-cornell approved these changes
Docs look ok to me

2024-03-15 13:22 UTC, mattdurham commented
Getting a few linting errors, the easiest way to check those is by running `USE_CONTAINER=1 make lint` from the repository root.

2024-03-21 18:24 UTC, blockloop commented
> Getting a few linting errors, the easiest way to check those is by running `USE_CONTAINER=1 make lint` from the repository root.

The linting errors don't show up for me locally, but I fixed the ones I found.

2024-03-25 13:52 UTC, mattdurham commented
Apologies, I have it set to automerge but everytime a change is pushed I have to manually kick off our drone build, outside contributions require manual kickoff. Will monitor this today to ensure it gets pushed in.

2024-03-25 16:01 UTC, blockloop commented
No problem. Looks like it all succeeded :)

2024-03-25 17:34 UTC, mattdurham approved these changes
lgtm

2024-03-25 17:35 UTC, merged